#!/bin/bash

# Data Gathering
# Header Info
HOSTNAME=$(hostname)
USERNAME=$(whoami)
DATE_TIME=$(date "+%Y-%m-%d %H:%M:%S")

# System Information
[ -f /etc/os-release ] && source /etc/os-release
OS="${NAME:-$(uname -s)} ${VERSION:-$(uname -r)}"

UPTIME=$(uptime -p | sed 's/^up //')
CPU=$(lscpu | grep "Model name:" | sed 's/Model name: *//' | xargs)
RAM=$(free -h | awk '/^Mem:/ {print $2}')

# Disks: Formats as "Name (Model) - Size" for all physical disks
DISKS=$(lsblk -d -o NAME,MODEL,SIZE | awk 'NR>1 {print $1, "(" $2 ")", "-", $3}' | paste -sd ", " -)

# Video Card 
VIDEO_RAW=$(lspci 2>/dev/null | grep -E "VGA|3D" | cut -d: -f3 | xargs)
VIDEO="${VIDEO_RAW:-Standard/Integrated Graphics}"

# Networking
DEFAULT_INT=$(ip route | grep default | awk '{print $5}' | head -n 1)
HOST_ADDRESS=$(ip -br addr show dev "$DEFAULT_INT" 2>/dev/null | awk '{print $3}' | cut -d/ -f1)
GATEWAY_IP=$(ip route | grep default | awk '{print $3}' | head -n 1)
DNS_SERVER=$(grep -i nameserver /etc/resolv.conf | awk '{print $2}' | paste -sd ", " -)

# System Status Phase

USERS_RAW=$(who | awk '{print $1}' | sort -u | paste -sd "," -)
USERS_LOGGED="${USERS_RAW:-None}"

# Disk Space format: /mountpoint FreeSize
DISK_SPACE=$(df -h --local 2>/dev/null | awk 'NR>1 && $6!~/^\/(boot|snap|sys|proc|dev)/ {print $6, $4}' | awk '{printf "%s %s, ", $1, $2}' | sed 's/, $//')

PROCESS_COUNT=$(ps -e | wc -l)
LOAD_AVERAGES=$(uptime | awk -F'load average:' '{print $2}' | xargs)

# Listening Ports (TCP/UDP numeric ports sorted cleanly)
LISTENING_PORTS=$(ss -tuln | awk 'NR>1 {print $5}' | awk -F: '{print $nf}' | grep -E '^[0-9]+$' | sort -nu | paste -sd ", " -)

# UFW Status (Evaluates status directly, suppresses errors if permission is denied)
UFW_RAW=$(sudo ufw status 2>/dev/null | head -n 1 | awk '{print $2}')
UFWSTATUS="${UFW_RAW:-Disabled/Inactive/No-Sudo}"


# Output Generation

# Padding the start with a blank line
echo ""

cat << EOF
System Report for $HOSTNAME generated by $USERNAME, on $DATE_TIME
 
System Information
------------------
OS: $OS
Uptime: $UPTIME
CPU: $CPU
RAM: $RAM
Disk(s): $DISKS
Video: $VIDEO
Host Address: $HOST_ADDRESS
Gateway IP: $GATEWAY_IP
DNS Server: $DNS_SERVER
 
System Status
-------------
Users Logged In: $USERS_LOGGED
Disk Space: $DISK_SPACE
Process Count: $PROCESS_COUNT
Load Averages: $LOAD_AVERAGES
Listening Network Ports: $LISTENING_PORTS
UFW Status: $UFWSTATUS
EOF

# Padding the end with a blank line
echo ""
